// Test Reveal_angular/src/app/view1/view1.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
declare let $: any;

@Component({
  selector: 'app-view1',
  templateUrl: './view1.component.html',
  styleUrls: ['./view1.component.scss']
})
export class View1Component {
  @ViewChild('revealView')
  public el!: ElementRef;

  public ngAfterViewInit(): void {
    $.ig.RevealSdkSettings.setBaseUrl("https://samples.revealbi.io/upmedia-backend/reveal-api/");
    $.ig.RVDashboard.loadDashboard("Sales", (dashboard) => {
      var revealView = new $.ig.RevealView("#revealView");
      revealView.dashboard = dashboard;

      var revealView1 = new $.ig.RevealView("#revealView1");
      revealView1.dashboard = dashboard;
    });
  }
}

<div class="column-layout group">
  <h5 class="h5">
    View 1
  </h5>
  <p class="text">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </p>
  <div id="revealView" style="height: 75%; width: 75%;"></div>
  <div id="revealView1" style="height: 75%; width: 75%;"></div>
</div>

// Test Reveal_webComponents/src/app/view1/view1.ts
import { html, css, LitElement, PropertyValueMap } from 'lit';
import { customElement, query } from 'lit/decorators.js';

declare let $: any;

@customElement('app-view1')
export default class View1 extends LitElement {
  static styles = css`
    :host {
      height: 100%;
      display: flex;
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
    }
    .column-layout {
      display: flex;
      flex-direction: column;
    }
    .group {
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
      position: relative;
      padding: 32px;
      min-width: 50px;
      min-height: 50px;
      flex-grow: 1;
      flex-basis: 0;
    }
    .h5 {
      margin: 0 0 16px;
      height: max-content;
      min-width: min-content;
    }
    .text {
      height: max-content;
      min-width: min-content;
    }
  `;

  firstUpdated() {
    const targetElement = this.renderRoot.querySelector('#revealView');
    $.ig.RevealSdkSettings.setBaseUrl("https://samples.revealbi.io/upmedia-backend/reveal-api/");

    $.ig.RVDashboard.loadDashboard("Sales", (dashboard: unknown) => {
      const revealView = new $.ig.RevealView(targetElement);
      revealView.dashboard = dashboard;
    });
  }

  render() {
    return html`
      <link href='https://fonts.googleapis.com/icon?family=Material+Icons' rel='stylesheet'>
      <link href='https://fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet'>
      <link rel='stylesheet' href='../../ig-theme.css'>
      <div class="column-layout group">
        <h5 class="h5">
          View 1
        </h5>
        <p class="typography__body-1 text">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>

        <div id="revealView" style="height: 75%; width: 75%;"></div>
      </div>
    `;
  }
}
